[package]
name = "witx-bindgen-cli"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[workspace]
members = [
  "crates/test-rust-wasm",
  "crates/test-wasmtime",
]

[dependencies]
anyhow = "1.0"
structopt = { version = "0.3", default-features = false }

witx-bindgen-gen-core = { path = 'crates/gen-core' }
witx-bindgen-gen-rust-wasm = { path = 'crates/gen-rust-wasm', features = ['structopt'] }
witx-bindgen-gen-wasmtime = { path = 'crates/gen-wasmtime', features = ['structopt'] }

[patch.crates-io]
witx = { git = 'https://github.com/sunfishcode/WASI', branch = 'abi-next-more' }
