[package]
name = "test-wasmtime"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
wasmtime = "0.26.0"
wasmtime-wasi = "0.26.0"
wasi-cap-std-sync = "0.26.0"
witx-bindgen-wasmtime = { path = "../wasmtime" }
