[package]
name = "witx-bindgen-wasmtime"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
bitflags = "1.2"
thiserror = "1.0"
wasmtime = "0.26.0"
witx-bindgen-wasmtime-impl = { path = "../wasmtime-impl", version = "0.1" }
